// <auto-generated />
using DashMq.DataAccess.Repositories;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DashMq.DataAccess.Migrations
{
    [DbContext(typeof(DashDbContext))]
    [Migration("20241013201834_AddedColumnDirection")]
    partial class AddedColumnDirection
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.8");

            modelBuilder.Entity("DashMq.DataAccess.Model.Datapoint", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<int>("Direction")
                        .HasColumnType("INTEGER")
                        .HasColumnName("direction");

                    b.Property<string>("Name")
                        .HasMaxLength(400)
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<string>("Topic")
                        .HasMaxLength(400)
                        .HasColumnType("TEXT")
                        .HasColumnName("topic");

                    b.HasKey("Id");

                    b.ToTable("datapoints", (string)null);
                });

            modelBuilder.Entity("DashMq.DataAccess.Model.DatapointValue", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<int>("DatapointId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("datapoint_id");

                    b.Property<long>("Timestamp")
                        .HasColumnType("INTEGER")
                        .HasColumnName("timestamp");

                    b.Property<double>("Value")
                        .HasColumnType("REAL")
                        .HasColumnName("value");

                    b.HasKey("Id");

                    b.HasIndex("DatapointId");

                    b.ToTable("datapoint_values", (string)null);
                });

            modelBuilder.Entity("DashMq.DataAccess.Model.DatapointValue", b =>
                {
                    b.HasOne("DashMq.DataAccess.Model.Datapoint", "Datapoint")
                        .WithMany()
                        .HasForeignKey("DatapointId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Datapoint");
                });
#pragma warning restore 612, 618
        }
    }
}
